/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.OvlascenoLice;
import domen.PoslovnaJedinica;
import domen.PravnoLice;
import domen.Vlasnik;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import logika.Kontroler;
import modeli.ModelTabelePravnaLica;
import modeli.ModelTabeleVlasnici;

/**
 *
 * @author Ivan
 */
public class DodajPravnoLiceForm extends javax.swing.JFrame {
private boolean izmena=false;
private boolean trazenNaziv=false;
private String naziv="";
private PravnoLice preIzmene=null;
ArrayList<Vlasnik> ObrsianiVlasci=new ArrayList<>();
    /**
     * Creates new form DodajPravnoLiceForm
     */
    public DodajPravnoLiceForm() {
        initComponents();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1tel = new javax.swing.JTextField();
        jTextField2adr = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1Vlasnici = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8Većinski = new javax.swing.JLabel();
        jButtonDodajVlas = new javax.swing.JButton();
        jTextField1maticni = new javax.swing.JTextField();
        jButtonObrisiVlasnika = new javax.swing.JButton();
        jTextField2naziv = new javax.swing.JTextField();
        jTextField3PIB = new javax.swing.JTextField();
        jButtonSavePravnoLice = new javax.swing.JButton();
        txtPrihodi = new javax.swing.JTextField();
        jButtonOtkazi = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxOvlasceno = new javax.swing.JComboBox();
        jTextField1email = new javax.swing.JTextField();
        jTextField1vecinski = new javax.swing.JTextField();
        jLabel4Status1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pravno lice");

        jTextField1tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1telActionPerformed(evt);
            }
        });

        jLabel1.setText("Matični broj");

        jLabel2.setText("Naziv");

        jLabel3.setText("PIB");

        jLabel5.setText("Adresa");

        jPanel1Vlasnici.setBorder(javax.swing.BorderFactory.createTitledBorder("Vlasnici pravnog lica"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1VlasniciLayout = new javax.swing.GroupLayout(jPanel1Vlasnici);
        jPanel1Vlasnici.setLayout(jPanel1VlasniciLayout);
        jPanel1VlasniciLayout.setHorizontalGroup(
            jPanel1VlasniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1VlasniciLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPanel1VlasniciLayout.setVerticalGroup(
            jPanel1VlasniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1VlasniciLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
        );

        jLabel6.setText("Telefon");

        jLabel7.setText("Email");

        jLabel8Većinski.setText("Većinski vlasnik");

        jButtonDodajVlas.setText("Dodaj");
        jButtonDodajVlas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajVlasActionPerformed(evt);
            }
        });

        jButtonObrisiVlasnika.setText("Obriši");
        jButtonObrisiVlasnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiVlasnikaActionPerformed(evt);
            }
        });

        jTextField2naziv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2nazivActionPerformed(evt);
            }
        });

        jButtonSavePravnoLice.setText("Sačuvaj pravno lice");
        jButtonSavePravnoLice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSavePravnoLiceActionPerformed(evt);
            }
        });

        jButtonOtkazi.setText("Otkaži");
        jButtonOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOtkaziActionPerformed(evt);
            }
        });

        jLabel4.setText("Ovlašeno lice ");

        jComboBoxOvlasceno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextField1email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1emailActionPerformed(evt);
            }
        });

        jTextField1vecinski.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1vecinskiActionPerformed(evt);
            }
        });

        jLabel4Status1.setText("Prihodi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4Status1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxOvlasceno, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3PIB, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPrihodi, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8Većinski)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1tel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1vecinski, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2adr, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1email, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonDodajVlas, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonObrisiVlasnika, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(242, 242, 242)
                            .addComponent(jButtonSavePravnoLice)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonOtkazi))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1Vlasnici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                    .addGap(14, 14, 14)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField2naziv, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                        .addComponent(jTextField1maticni))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))))))
                    .addContainerGap(54, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField2adr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3PIB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1vecinski, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrihodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4Status1)
                            .addComponent(jLabel8Većinski))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxOvlasceno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(jButtonDodajVlas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonObrisiVlasnika)
                .addContainerGap(278, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel5)
                        .addComponent(jTextField1maticni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel6)
                        .addComponent(jTextField2naziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jLabel7)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                    .addComponent(jPanel1Vlasnici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(9, 9, 9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonSavePravnoLice)
                        .addComponent(jButtonOtkazi))
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1telActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1telActionPerformed

    private void jTextField2nazivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2nazivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2nazivActionPerformed

    private void jButtonOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOtkaziActionPerformed
PravnaLicaForm pl=new PravnaLicaForm();
this.setVisible(false);
pl.setVisible(true);
    }//GEN-LAST:event_jButtonOtkaziActionPerformed

    private void jTextField1emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1emailActionPerformed

    private void jTextField1vecinskiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1vecinskiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1vecinskiActionPerformed

    private void jButtonObrisiVlasnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiVlasnikaActionPerformed
int red=jTable1.getSelectedRow();
        if(red!=-1){
      
            ModelTabeleVlasnici mtv=(ModelTabeleVlasnici) jTable1.getModel();
            Vlasnik v=mtv.getLista().get(red);
            ObrsianiVlasci.add(v);
            mtv.obrisi(red);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Niste izabrali vlasnika!");
            return;
        }
    }//GEN-LAST:event_jButtonObrisiVlasnikaActionPerformed

    private void jButtonDodajVlasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajVlasActionPerformed
VlasnikForm vf=new VlasnikForm(this, true);
vf.pack();
vf.setVisible(true);
    }//GEN-LAST:event_jButtonDodajVlasActionPerformed

    private void jButtonSavePravnoLiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSavePravnoLiceActionPerformed
ModelTabeleVlasnici mtv=(ModelTabeleVlasnici) jTable1.getModel();
        if(izmena){
 if(jTextField1tel.getText().isEmpty()||jTextField1vecinski.getText().isEmpty()){
               JOptionPane.showMessageDialog(this, "Niste uneli sve podatke!");
                 return;
    }
    ArrayList<Vlasnik> lista=mtv.getLista();
  
   String vecinski =  jTextField1vecinski.getText();
   String telefon =  jTextField1tel.getText();
    String maticni=jTextField1maticni.getText();
       OvlascenoLice ovlasceno = (OvlascenoLice) jComboBoxOvlasceno.getSelectedItem();
      int maticniBroj=0;
    try{
        maticniBroj=Integer.parseInt(maticni);
    } catch ( NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Niste uneli maticni broj ispravno!");
        return;
    }
       long tel=0;
    try{
        tel=Long.parseLong(telefon);
    } catch ( NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Niste uneli telefon ispravno!");
        return;
    }
    
    if(!(this.getPreIzmene().getNajveci_procenat_vlasnik().equals(vecinski))){
     boolean trig=Kontroler.getInstanca().izmeniVecinskogVlasnika(maticniBroj,vecinski);
if(!trig){
        JOptionPane.showMessageDialog(this, "Ne moze se direktno izmeniti najveci vlasnik!");
        jTextField1vecinski.setText(this.getPreIzmene().getNajveci_procenat_vlasnik());
        return;

}else {
        JOptionPane.showMessageDialog(this, "Triger ne radi!");
return;
}
    }
    PravnoLice pl=new PravnoLice(maticniBroj, "", 0, "", tel, "", 0, "", ovlasceno, lista);
            for (Vlasnik vlasnik : lista) {
                vlasnik.setMaticni_broj(maticniBroj);
            }
    boolean uspesno=Kontroler.getInstanca().izmeniPravnoLive(pl,lista,getPreIzmene(),ObrsianiVlasci);
if(uspesno){
        JOptionPane.showMessageDialog(this, "Uspesno sacuvano!");
        
        PravnaLicaForm plf=new PravnaLicaForm();
        plf.setVisible(true);
        this.setVisible(false);

}else {
        JOptionPane.showMessageDialog(this, "Nije uspesno sacuvano!");

}
}else{
             if(jTextField1email.getText().isEmpty()||jTextField1maticni.getText().isEmpty()||jTextField1tel.getText().isEmpty()||jTextField2adr.getText().isEmpty()||jTextField2naziv.getText().isEmpty()||jTextField3PIB.getText().isEmpty()||txtPrihodi.getText().isEmpty()){
               JOptionPane.showMessageDialog(this, "Niste uneli sve podatke!");
                 return;
    }
    ArrayList<Vlasnik> lista=mtv.getLista();
  String email =jTextField1email.getText();
   String maticni =  jTextField1maticni.getText();
   String telefon =  jTextField1tel.getText();
    String adresa = jTextField2adr.getText();
    String naziv = jTextField2naziv.getText();
    String PIB = jTextField3PIB.getText();
     String prihodi = txtPrihodi.getText();
    OvlascenoLice ovlasceno = (OvlascenoLice) jComboBoxOvlasceno.getSelectedItem();
    int maticniBroj=0;
    try{
        maticniBroj=Integer.parseInt(maticni);
    } catch ( NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Niste uneli maticni broj ispravno!");
        return;
    }
     long tel=0;
    try{
        tel=Long.parseLong(telefon);
    } catch ( NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Niste uneli telefon ispravno!");
        return;
    }
     int PIBbr=0;
    try{
       PIBbr=Integer.parseInt(PIB);
    } catch ( NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Niste uneli PIB ispravno!");
        return;
    }
     int prih=0;
    try{
        prih=Integer.parseInt(prihodi);
    } catch ( NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Niste uneli prihode ispravno!");
        return;
    }
    PravnoLice pl=new PravnoLice(maticniBroj, naziv, PIBbr, adresa, tel, email, prih, "", ovlasceno, lista);
boolean uspesno=Kontroler.getInstanca().sacuvajPravnoLive(pl,lista);
if(uspesno){
        JOptionPane.showMessageDialog(this, "Uspesno sacuvano!");
       if(this.isTrazenNaziv()){
       DodajZahtevForm dzf=new DodajZahtevForm();
       dzf.setPravnoLice(pl);
       dzf.srediFormu(null, uspesno);
       dzf.setVisible(true);
       this.setVisible(false);
       }else{
        PravnaLicaForm plf=new PravnaLicaForm();
        plf.setVisible(true);
        this.setVisible(false);
       }
}else {
        JOptionPane.showMessageDialog(this, "Nije uspesno sacuvano!");

}
}
    }//GEN-LAST:event_jButtonSavePravnoLiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DodajPravnoLiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DodajPravnoLiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DodajPravnoLiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DodajPravnoLiceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DodajPravnoLiceForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajVlas;
    private javax.swing.JButton jButtonObrisiVlasnika;
    private javax.swing.JButton jButtonOtkazi;
    private javax.swing.JButton jButtonSavePravnoLice;
    private javax.swing.JComboBox jComboBoxOvlasceno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel4Status1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8Većinski;
    private javax.swing.JPanel jPanel1Vlasnici;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1email;
    private javax.swing.JTextField jTextField1maticni;
    private javax.swing.JTextField jTextField1tel;
    private javax.swing.JTextField jTextField1vecinski;
    private javax.swing.JTextField jTextField2adr;
    private javax.swing.JTextField jTextField2naziv;
    private javax.swing.JTextField jTextField3PIB;
    private javax.swing.JTextField txtPrihodi;
    // End of variables declaration//GEN-END:variables

    

    void srediFormu(PravnoLice pl, boolean prikazi) {
if(pl==null){
    srediKombo(null);
    srediTabelu(null);
    jTextField1vecinski.setEditable(false);
    if(isTrazenNaziv()){
    jTextField2naziv.setText(getNaziv());
    jTextField2naziv.setEditable(false);
    }
}else{
    this.setPreIzmene(pl);
    srediKombo(pl);
    srediTabelu(pl);
    if(prikazi){
     jTextField1email.setText(pl.getEmail());
     jTextField1maticni.setText(pl.getMaticni_broj()+"");
     jTextField1tel.setText(pl.getTelefon()+"");
     jTextField1vecinski.setText(pl.getNajveci_procenat_vlasnik());
     jTextField2adr.setText(pl.getAdresa());
     jTextField2naziv.setText(pl.getNaziv());
     jTextField3PIB.setText(pl.getPIB()+"");
     txtPrihodi.setText(pl.getPrihodi()+"");
     jTextField1email.setEditable(false);
     jTextField1maticni.setEditable(false);
     jTextField1tel.setEditable(false);
//     jTextField1vecinski.setEditable(false);
     jTextField2adr.setEditable(false);
     jTextField2naziv.setEditable(false);
     jTextField3PIB.setEditable(false);
     txtPrihodi.setEditable(false);
     jComboBoxOvlasceno.setEditable(false);
jButtonDodajVlas.setVisible(false);
jButtonObrisiVlasnika.setVisible(false);
jButtonSavePravnoLice.setVisible(false);
    }else{
        
    jTextField1email.setText(pl.getEmail());
     jTextField1maticni.setText(pl.getMaticni_broj()+"");
     jTextField1tel.setText(pl.getTelefon()+"");
     jTextField1vecinski.setText(pl.getNajveci_procenat_vlasnik());
     jTextField2adr.setText(pl.getAdresa());
     jTextField2naziv.setText(pl.getNaziv());
     jTextField3PIB.setText(pl.getPIB()+"");
     txtPrihodi.setText(pl.getPrihodi()+"");
     jTextField1email.setEditable(false);
     jTextField1maticni.setEditable(false);
     jTextField1tel.setEditable(false);
     jTextField1vecinski.setEditable(true);
     jTextField2adr.setEditable(false);
     jTextField2naziv.setEditable(false);
     jTextField3PIB.setEditable(false);
     txtPrihodi.setEditable(false);
     jComboBoxOvlasceno.setEditable(true);
    }



}

    }

    private void srediKombo(PravnoLice pl) {
        //kod dodaje ide null
ArrayList<OvlascenoLice> lista = Kontroler.getInstanca().dajMiListuOvlascenih();

        jComboBoxOvlasceno.removeAllItems();
        if(pl!=null)        
lista.remove(pl.getOl());
        if(pl!=null)        
        jComboBoxOvlasceno.addItem(pl.getOl());
        for (OvlascenoLice ol : lista) {
            jComboBoxOvlasceno.addItem(ol);
        }
    }
    private void srediTabelu(PravnoLice pl ) {
//null kod dodaje
ArrayList<Vlasnik> lista=new ArrayList<>();
if(pl==null){
ModelTabeleVlasnici mtv=new ModelTabeleVlasnici();
jTable1.setModel(mtv);
} else
{
    lista=Kontroler.getInstanca().vratiVlasnike(pl);
   getPreIzmene().setVlasnici(lista);
ModelTabeleVlasnici mtv=new ModelTabeleVlasnici(lista);
jTable1.setModel(mtv);
}
    }

    public boolean isIzmena() {
        return izmena;
    }

    public void setIzmena(boolean izmena) {
        this.izmena = izmena;
    }
    public void dodajVlasnika(Vlasnik v){
    ModelTabeleVlasnici mtv=(ModelTabeleVlasnici) jTable1.getModel();
    mtv.dodaj(v);
    }

    public PravnoLice getPreIzmene() {
        return preIzmene;
    }

    public void setPreIzmene(PravnoLice preIzmene) {
        this.preIzmene = preIzmene;
    }

    public boolean isTrazenNaziv() {
        return trazenNaziv;
    }

    public void setTrazenNaziv(boolean trazenNaziv) {
        this.trazenNaziv = trazenNaziv;
    }

    public String getNaziv() {
        return naziv;
    }

    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    
}
