/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.KorisnikKartice;
import domen.Vlasnik;
import javax.swing.JOptionPane;

/**
 *
 * @author Ivan
 */
public class KorisnikKarticeForm extends javax.swing.JDialog {

    /**
     * Creates new form KorisnikKarticeForm
     */
    public KorisnikKarticeForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        srediKombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Limit = new javax.swing.JLabel();
        Sačuvaj = new javax.swing.JButton();
        jTextField2Ime = new javax.swing.JTextField();
        jTextField3JMBG = new javax.swing.JTextField();
        jTextField4Limit = new javax.swing.JTextField();
        jComboBox1Vrsta = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Korisnik kartice");

        jLabel2.setText("Ime i prezime");

        jLabel3.setText("JMBG");

        jLabel4.setText("Vrsta kartice");

        Limit.setText("Limit kartice (RSD)");

        Sačuvaj.setText("Sačuvaj");
        Sačuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SačuvajActionPerformed(evt);
            }
        });

        jTextField4Limit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4LimitActionPerformed(evt);
            }
        });

        jComboBox1Vrsta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Otkazi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(Limit))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField4Limit)
                    .addComponent(jComboBox1Vrsta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField3JMBG)
                    .addComponent(jTextField2Ime))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(Sačuvaj)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2Ime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3JMBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1Vrsta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Limit)
                    .addComponent(jTextField4Limit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sačuvaj)
                    .addComponent(jButton1))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4LimitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4LimitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4LimitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SačuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SačuvajActionPerformed
 if(jTextField2Ime.getText().isEmpty()||jTextField3JMBG.getText().isEmpty()||jTextField4Limit.getText().isEmpty()){
              JOptionPane.showMessageDialog(this, "Niste uneli sve podatke!");

        return;
    }
    String ime=jTextField2Ime.getText();
    String JMBG=jTextField3JMBG.getText();
    String limit=jTextField4Limit.getText();
    String vrsta=(String) jComboBox1Vrsta.getSelectedItem();
    
    int lim=0;
    try{
        lim=Integer.parseInt(limit);
    } catch ( NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Niste uneli limit ispravno!");
        return;
    }
    if(lim<0){
    JOptionPane.showMessageDialog(this, "Niste uneli limit ispravno!");
        return;
    }
    long jmb=0;
    try{
        jmb=Long.parseLong(JMBG);
    } catch ( NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Niste uneli JMBG ispravno!");
        return;
    }
    if((JMBG.length()<12) || (JMBG.length() >13)){
    JOptionPane.showMessageDialog(this, "Niste uneli JMBG ispravno!");
        return;
    }
   
KorisnikKartice kk=new KorisnikKartice(JMBG, ime, vrsta, "", lim, -1);
    DodajZahtevForm dzf= (DodajZahtevForm) this.getParent();
    dzf.dodajKorisnika(kk);
            // TODO add your handling code here:
    }//GEN-LAST:event_SačuvajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KorisnikKarticeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KorisnikKarticeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KorisnikKarticeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KorisnikKarticeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                KorisnikKarticeForm dialog = new KorisnikKarticeForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Limit;
    private javax.swing.JButton Sačuvaj;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1Vrsta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField2Ime;
    private javax.swing.JTextField jTextField3JMBG;
    private javax.swing.JTextField jTextField4Limit;
    // End of variables declaration//GEN-END:variables

    private void srediKombo() {
jComboBox1Vrsta.removeAllItems();
jComboBox1Vrsta.addItem("MasterCard");
jComboBox1Vrsta.addItem("Visa");

    }
}
